databases:
  - name: ref_network
    databaseName: ref_network_production
    user: tyler

services:
  - type: web
    name: ref_network
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ref_network
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
